service: auth

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.6
  stage: ${env:ENVIRONMENT}
  region: us-east-2


plugins:
  - serverless-python-requirements
  - serverless-wsgi
package:
  individually: true


custom:
  wsgi:
    app: app.app
    packRequirements: false


functions:
  auth:
    name: auth-${env:ENVIRONMENT}
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
    description: auth-lambda
    timeout: 10 # seconds
    memorySize: 128 #mb
    environment:
      REGION: ${env:AWS_REGION}
      ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    package:
      patterns:
        - "!node_modules/**"
        - "!package-lock.json"
        - "!package.json"