service: auth

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.6
  stage: ${env:ENVIRONMENT}
  region: us-east-2
  vpc:
    securityGroupIds:
      - sg-0ee8e7ff484435ac7
    subnetIds:
      - subnet-0b24323ea0f80a90c
      - subnet-0fac506d1fede091d
      - subnet-02322f8a56640ad81


plugins:
  - serverless-python-requirements
  - serverless-wsgi
package:
  individually: true


custom:
  wsgi:
    app: app.app
    packRequirements: false


functions:
  auth:
    name: auth-${env:ENVIRONMENT}
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
    description: auth-lambda
    timeout: 30 # seconds
    memorySize: 128 #mb
    environment:
      REGION: ${env:AWS_REGION}
      ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
      host_db: ${env:host_db}
      password_db: ${env:password_db}
      user_db: ${env:user_db}
      database: ${env:database}
    package:
      patterns:
        - "!node_modules/**"
        - "!package-lock.json"
        - "!package.json"