"""empty message

Revision ID: 24c0f0c5098c
Revises: 4d6a802eb8db
Create Date: 2022-08-24 19:20:24.780096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c0f0c5098c'
down_revision = '4d6a802eb8db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
