"""empty message

Revision ID: 4485b6a617ab
Revises: 7969c07dba6f
Create Date: 2022-08-15 14:55:09.698022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4485b6a617ab'
down_revision = '7969c07dba6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_constraint('users_profile_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_profile_id_fkey', 'users', 'profiles', ['profile_id'], ['id'])
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
