"""empty message

Revision ID: d20a8f15aa12
Revises: 24c0f0c5098c
Create Date: 2022-08-24 19:21:45.970397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20a8f15aa12'
down_revision = '24c0f0c5098c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
