"""empty message

Revision ID: f26598d0bd07
Revises: 9be886fe78c3
Create Date: 2022-08-24 12:58:01.268074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26598d0bd07'
down_revision = '9be886fe78c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_try_invalid', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_try_invalid')
    op.drop_column('users', 'attempts')
    # ### end Alembic commands ###
