from enum import Enum


class RolesEnum(Enum):
    PROFILES_MANAGEMENT = 'PROFILES_MANAGEMENT'
    USER_MANAGEMENT = 'USER_MANAGEMENT'
    DELETE_PROFILES = 'DELETE_PROFILES'
    DELETE_ROLES = 'DELETE_ROLES'
    CREATE_PROFILES = 'CREATE_PROFILES'
    READ_PROFILES = 'READ_PROFILES'
    CREATE_ROLES = 'CREATE_ROLES'
    READ_ROLES = 'READ_ROLES'